# Based on the "trust" template v0.1.1
# https://github.com/japaric/trust/tree/v0.1.1

environment:
  global:
    RUST_VERSION: stable
    CRATE_NAME: livesplit-core

  matrix:
    # MinGW
    - TARGET: i686-pc-windows-gnu
    - TARGET: x86_64-pc-windows-gnu

    # MSVC
    - TARGET: i686-pc-windows-msvc
    - TARGET: x86_64-pc-windows-msvc

    # Testing other channels
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: beta
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: beta
    - TARGET: x86_64-pc-windows-gnu
      RUST_VERSION: nightly
    - TARGET: x86_64-pc-windows-msvc
      RUST_VERSION: nightly

matrix:
  allow_failures:
    - RUST_VERSION: nightly
    - RUST_VERSION: beta

install:
  - ps: >-
      choco install curl
  - curl -sSf -o rustup-init.exe https://win.rustup.rs/
  - rustup-init.exe -y --default-host %TARGET% --default-toolchain %RUST_VERSION%
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

test_script:
  # we don't run the "test phase" when doing deploys
  - if [%APPVEYOR_REPO_TAG%]==[false] (
      cargo build -p staticlib --target %TARGET% &&
      cargo build -p cdylib --target %TARGET% &&
      cargo test -p livesplit-core --target %TARGET%
    )

before_deploy:
  - cargo rustc -p staticlib --target %TARGET% --release
  - cargo rustc -p cdylib --target %TARGET% --release
  - ps: ci\before_deploy.ps1

deploy:
  artifact: /.*\.zip/
  auth_token:
    secure: zZGfrpCR/0TmHcXPwar4hOx6pZeq3C9Wwf/g62pvf135tAwJIVpuZHJjB0sAAd2M
  description: ''
  on:
    RUST_VERSION: stable
    appveyor_repo_tag: true
  provider: GitHub

# Don't cache on appveyor, as it seems to blow the disk storage every now and then.
# cache:
#   - C:\Users\appveyor\.cargo\registry
#   - target

# branches:
#   only:
#     # Release tags
#     - /^v\d+\.\d+\.\d+.*$/
#     - master

notifications:
  - provider: Email
    on_build_success: false

# disable automatic builds
build: false
