[package]
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
name = "bindings"
version = "0.1.0"
edition = "2018"

[dependencies]
heck = "0.3.0"
structopt = "0.2.9"
structopt-derive = "0.2.9"
syn = { version = "0.15.1", default-features = false, features = ["parsing", "full", "printing"] }
