[package]
authors = ["Christopher Serr <christopher.serr@gmail.com>"]
name = "bindings"
version = "0.1.0"

[dependencies]
heck = "0.2.1"
structopt = "0.1.0"
structopt-derive = "0.1.0"
syn = { version = "0.12.10", default-features = false, features = ["parsing", "full"] }
