[package]
name = "hotkey"
version = "0.1.0"
authors = ["Christopher Serr <christopher.serr@gmail.com>"]

[target.'cfg(windows)'.dependencies]
winapi = "0.2.8"
user32-sys = "0.2.0"
kernel32-sys = "0.2.2"

[dependencies]
